In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
data = pd.read_csv("data2.csv")
data.info()

FileNotFoundError: [Errno 2] No such file or directory: 'data2.csv'

In [ ]:
data.head()

,Marca temporal,Correo,Semestre,Carrera,Regular,Ciudad,Hermanos,Marca,Modelo,Capacidad,Metodo_pago,Tiempo,Estado,Gender,Trabajo,Edad,Telefono_futuro
0,03/09/2026 17:30,fespinozagarcia0105@gmail.com,Tercero,Ciencia de Datos,NaN,Estado de México,NaN,Honor,Honor x7a,128 GB,Plan,Entre 2 y 3 años,Nuevo,Mujer,Sí,21,NaN
1,03/09/2026 18:02,gisellemerino2702@gmail.com,Tercero,Ciencia de Datos,NaN,Estado de México,NaN,Apple,15 pro max,256 GB,Prepago,Entre 6 meses y 1 año,Nuevo,Mujer,No,21,NaN
2,03/09/2026 18:19,mildredcaravantes@gmail.com,Primero,Ciencia de Datos,NaN,Estado de México,NaN,Apple,iphone 16 pro max,256 GB,Plan,Entre 1 y 2 años,Nuevo,Mujer,No,20,NaN
3,03/09/2026 18:37,garcia.hernandez.edgar.alessandro@gmail.com,Tercero,Ciencia de Datos,NaN,CDMX,NaN,Apple,iPhone 16 Pro Max,256 GB,Plan,Entre 1 y 2 años,Nuevo,Hombre,No,19,NaN
4,03/09/2026 20:56,diegobus022@gmail.com,Tercero,Ciencia de Datos,NaN,Otro,NaN,Apple,iPhone 13 Pro max,512 GB,Prepago,Entre 1 y 2 años,Segunda mano,Hombre,No,19,NaN

In [ ]:
data.describe()

,Marca temporal,Correo,Semestre,Carrera,Regular,Ciudad,Hermanos,Marca,Modelo,Capacidad,Metodo_pago,Tiempo,Estado,Gender,Trabajo,Edad,Telefono_futuro
count,511,511,511,511,482,511,482,511,511,511,511,511,511,511,511,511,481
unique,380,511,8,4,2,18,2,13,388,7,2,5,2,2,2,8,15
top,03/12/2026 15:21,fespinozagarcia0105@gmail.com,Cuarto,Ingeniería en Sistemas,Sí,CDMX,Sí,Apple,iPhone 14,256 GB,Plan,Entre 1 y 2 años,Nuevo,Hombre,No,19,Samsung
freq,13,1,113,267,290,275,410,152,9,195,305,163,436,374,341,131,180

In [ ]:
print("Dimensiones del dataset:", data.shape)
print("Número de filas:", data.shape[0])
print("Número de columnas:", data.shape[1])

Dimensiones del dataset: (511, 17)
Número de filas: 511
Número de columnas: 17

In [ ]:
print(data.notnull().sum())

Marca temporal     511
Correo             511
Semestre           511
Carrera            511
Regular            482
Ciudad             511
Hermanos           482
Marca              511
Modelo             511
Capacidad          511
Metodo_pago        511
Tiempo             511
Estado             511
Gender             511
Trabajo            511
Edad               511
Telefono_futuro    481
dtype: int64

In [ ]:
print(data["Modelo"].value_counts())

Modelo
iPhone 14            9
A54                  9
S24                  8
A56                  7
iPhone 12            6
                    ..
5522644535           1
Samsung S24 Ultra    1
g71 5G               1
5611263561           1
POCO X5 5G           1
Name: count, Length: 388, dtype: int64

In [ ]:
print(data.columns)
data["Semestre"]=data["Semestre"].map({
    "Primero":1,
    "Segundo":2,
    "Tercero":3,
    "Cuarto":4,
    "Quinto":5,
    "Sexto":6,
    "Septimo":7,
    "Octavo":8
})
data["Carrera"]=data["Carrera"].map({
    "Ciencia de Datos":1,
    "Inteligencia Artificial":2,
    "Ingeniería en Sistemas":3
})
data["Regular"]=data["Regular"].map({
    "No":0,
    "Sí":1
})
data["Hermanos"]=data["Hermanos"].map({
    "No":0,
    "Sí":1
})
data["Capacidad"]=data["Capacidad"].map({
    "256 GB":256,
    "128 GB":128,
    "64 GB":64,
    "512 GB":512,
    "32 GB":32,
    "1 TB":1,
    "2 TB":2
})
data["Metodo_pago"]=data["Metodo_pago"].map({
    "Plan":1,
    "Prepago":0
})
data["Tiempo"]=data["Tiempo"].map({
    "Menos de 6 meses":0,
    "Entre 6 meses y 1 año":1,
    "Entre 1 y 2 años":2,
    "Entre 2 y 3 años":3,
    "Más de 3 años":4
})
data["Estado"]=data["Estado"].map({
    "Nuevo":1,
    "Segunda mano":0
})
data["Gender"]=data["Gender"].map({
    "Mujer":0,
    "Hombre":1
})
data["Trabajo"]=data["Trabajo"].map({
    "Sí":1,
    "No":0
})
data["Edad"]=data["Edad"].replace({
    "24 o más":24
})
data.loc[
    data["Modelo"] == "iPhone 17 pro Max de 2T, color negro 💋",
    "Capacidad"
] = 2
data["Modelo"] = data["Modelo"].replace({
    "iPhone 17 pro Max de 2T, color negro 💋": "iPhone 17 Pro Max"
})

Index(['Marca temporal', 'Correo', 'Semestre', 'Carrera', 'Regular', 'Ciudad',
       'Hermanos', 'Marca', 'Modelo', 'Capacidad', 'Metodo_pago', 'Tiempo',
       'Estado', 'Gender', 'Trabajo', 'Edad', 'Telefono_futuro'],
      dtype='str')

In [ ]:
data["Edad"].value_counts()

Edad
19    131
20    109
21     84
22     61
18     59
24     40
23     24
17      3
Name: count, dtype: int64

In [ ]:
data

,Marca temporal,Correo,Semestre,Carrera,Regular,Ciudad,Hermanos,Marca,Modelo,Capacidad,Metodo_pago,Tiempo,Estado,Gender,Trabajo,Edad,Telefono_futuro
0,03/09/2026 17:30,fespinozagarcia0105@gmail.com,3.0,1.0,NaN,Estado de México,NaN,Honor,Honor x7a,128,1,3,1,0,1,21,NaN
1,03/09/2026 18:02,gisellemerino2702@gmail.com,3.0,1.0,NaN,Estado de México,NaN,Apple,15 pro max,256,0,1,1,0,0,21,NaN
2,03/09/2026 18:19,mildredcaravantes@gmail.com,1.0,1.0,NaN,Estado de México,NaN,Apple,iphone 16 pro max,256,1,2,1,0,0,20,NaN
3,03/09/2026 18:37,garcia.hernandez.edgar.alessandro@gmail.com,3.0,1.0,NaN,CDMX,NaN,Apple,iPhone 16 Pro Max,256,1,2,1,1,0,19,NaN
4,03/09/2026 20:56,diegobus022@gmail.com,3.0,1.0,NaN,Otro,NaN,Apple,iPhone 13 Pro max,512,0,2,0,1,0,19,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,3/18/2026 16:05:40,gonzalez.leonardo.vv06@gmail.com,3.0,1.0,1.0,Estado de México,1.0,Motorola,g71 5G,128,1,3,1,1,0,20,Motorola
507,3/18/2026 16:38:14,martinez.salinas.emiliano1@gmail.com,6.0,1.0,1.0,CDMX,1.0,Apple,5611263561,256,1,3,1,1,1,20,Apple
508,3/18/2026 16:41:03,isaactoramd1@gmail.com,6.0,1.0,0.0,Estado de México,1.0,Xiaomi,POCO X5 5G,256,1,3,1,1,0,23,Otra
509,3/18/2026 16:42:08,reginanovelo2003@gmail.com,6.0,1.0,1.0,Estado de México,1.0,Apple,iPhone 16,256,1,2,1,0,1,22,Apple
510,3/18/2026 18:49:24,ruligamarons@gmail.com,6.0,1.0,1.0,CDMX,0.0,Samsung,S21,256,0,4,1,1,0,23,Samsung

In [ ]:
# Convertir a DataFrame y guardar como archivo de texto
data["Modelo"].value_counts().to_csv('conteo_modelos.txt', sep='\t', header=True)

In [ ]:
data[["Marca", "Tiempo", "Modelo","Capacidad"]].value_counts().to_csv(
    "conteo.txt", sep="\t", header=True
)